/**
 * Right-side artifact panel — the WorkBuddy-style split-pane sidebar
 * shown next to the Chat conversation.  Hosts three top-level tabs:
 *
 *   - 变更 (changes): side-by-side diff for the focused file only (no
 *     in-panel file list — open a file from the run’s file cards below
 *     the graph, or “查看文件变更” picks the latest change).
 *   - 预览 (preview): rendered preview of whichever file is currently
 *     focused (Markdown → rendered, code → syntax-highlighted).  Shares
 *     `focusedFile` with the changes tab so switching tabs keeps
 *     context.
 *   - 工作空间 (browser): read-only workspace tree + file preview,
 *     scoped to the current agent's `agent.workspace`.
 *
 * Open/close + tab + focused-file state lives in the
 * `useArtifactPanel` zustand store so any part of the page (file cards,
 * toolbar buttons, "查看文件变更 →" links) can drive it.
 */
import { useLayoutEffect, useMemo } from 'react';
import { Eye, FileEdit, FolderTree, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import type { GeneratedFile } from '@/lib/generated-files';
import type { AgentSummary } from '@/types/agent';
import { useArtifactPanel } from '@/stores/artifact-panel';
import type { FilePreviewTarget } from './types';
import { FilePreviewBody } from './FilePreviewBody';
import { WorkspaceBrowserBody } from './WorkspaceBrowserBody';
import { WORKSPACE_BROWSER_ENABLED } from './workspace-browser-config';

export interface ArtifactPanelProps {
  /** All files generated by the AI across the conversation. */
  files: GeneratedFile[];
  /** Currently selected agent (drives the workspace tab). */
  agent: AgentSummary | null;
  /** Used to mark "本轮新增" badges on the workspace tree. */
  runStartedAt?: number | null;
  /** Bumping this number triggers a workspace tree reload. */
  refreshSignal?: number;
}

export function ArtifactPanel({ files, agent, runStartedAt, refreshSignal }: ArtifactPanelProps) {
  const { t } = useTranslation('chat');
  const tab = useArtifactPanel((s) => s.tab);
  const visibleTab = !WORKSPACE_BROWSER_ENABLED && tab === 'browser' ? 'changes' : tab;
  const setTab = useArtifactPanel((s) => s.setTab);
  const focusedFile = useArtifactPanel((s) => s.focusedFile);
  const setFocusedFile = useArtifactPanel((s) => s.setFocusedFile);
  const close = useArtifactPanel((s) => s.close);

  return (
    <div className="flex h-full min-h-0 flex-col bg-background">
      <div className="flex shrink-0 items-center justify-between gap-2 border-b border-black/5 px-3 py-2 dark:border-white/10">
        <div className="flex min-w-0 items-center gap-1">
          <PanelTabButton
            icon={<FileEdit className="h-3.5 w-3.5" />}
            label={t('artifactPanel.tabs.changes', '变更')}
            active={visibleTab === 'changes'}
            onClick={() => setTab('changes')}
          />
          <PanelTabButton
            icon={<Eye className="h-3.5 w-3.5" />}
            label={t('artifactPanel.tabs.preview', '预览')}
            active={visibleTab === 'preview'}
            onClick={() => setTab('preview')}
          />
          {WORKSPACE_BROWSER_ENABLED && (
            <PanelTabButton
              icon={<FolderTree className="h-3.5 w-3.5" />}
              label={t('artifactPanel.tabs.browser', '工作空间')}
              active={visibleTab === 'browser'}
              onClick={() => setTab('browser')}
            />
          )}
        </div>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="h-7 w-7 shrink-0"
          onClick={close}
          aria-label={t('filePreview.actions.close', '关闭')}
        >
          <X className="h-4 w-4 pointer-events-none" />
        </Button>
      </div>

      <div className="min-h-0 flex-1">
        {visibleTab === 'changes' && (
          <ChangesTab
            files={files}
            focusedFile={focusedFile}
            onFocus={(f) => setFocusedFile(f)}
          />
        )}
        {visibleTab === 'preview' && <PreviewTab focusedFile={focusedFile} />}
        {WORKSPACE_BROWSER_ENABLED && visibleTab === 'browser' && (
          <WorkspaceBrowserBody
            agent={agent}
            runStartedAt={runStartedAt}
            refreshSignal={refreshSignal}
            compact
          />
        )}
      </div>
    </div>
  );
}

interface PanelTabButtonProps {
  icon: React.ReactNode;
  label: string;
  active: boolean;
  onClick: () => void;
}

function PanelTabButton({ icon, label, active, onClick }: PanelTabButtonProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-medium transition-colors',
        active
          ? 'bg-foreground/10 text-foreground'
          : 'text-muted-foreground hover:bg-black/5 hover:text-foreground dark:hover:bg-white/10',
      )}
    >
      {icon}
      <span>{label}</span>
    </button>
  );
}

function generatedFileToTarget(file: GeneratedFile): FilePreviewTarget {
  return {
    filePath: file.filePath,
    fileName: file.fileName,
    ext: file.ext,
    mimeType: file.mimeType,
    contentType: file.contentType,
    action: file.action,
    fullContent: file.fullContent,
    baseline: file.baseline,
    edits: file.edits,
  };
}

interface ChangesTabProps {
  files: GeneratedFile[];
  focusedFile: FilePreviewTarget | null;
  onFocus: (file: FilePreviewTarget) => void;
}

/**
 * Full-width diff for the focused file.  Which file is focused comes from
 * the run’s file cards or “查看文件变更 →” (auto-first); switching workspace
 * tabs does not bring back a sidebar list.
 */
function ChangesTab({ files, focusedFile, onFocus }: ChangesTabProps) {
  const { t } = useTranslation('chat');

  // De-dup files by path, keep the latest entry (highest lastSeenIndex).
  const uniqueFiles = useMemo(() => {
    const map = new Map<string, GeneratedFile>();
    for (const f of files) {
      const existing = map.get(f.filePath);
      if (!existing || f.lastSeenIndex >= existing.lastSeenIndex) map.set(f.filePath, f);
    }
    return Array.from(map.values()).sort((a, b) => b.lastSeenIndex - a.lastSeenIndex);
  }, [files]);

  // Auto-select the first file when entering this tab without one in
  // focus (or when the focused file disappears, e.g. session reset).
  useLayoutEffect(() => {
    if (uniqueFiles.length === 0) return;
    const stillExists =
      focusedFile && uniqueFiles.some((f) => f.filePath === focusedFile.filePath);
    if (!stillExists) {
      onFocus(generatedFileToTarget(uniqueFiles[0]));
    }
  }, [focusedFile, uniqueFiles, onFocus]);

  if (uniqueFiles.length === 0) {
    return (
      <div className="flex h-full items-center justify-center px-6 text-center text-sm text-muted-foreground">
        {t('artifactPanel.changes.empty', '本会话尚无文件变更')}
      </div>
    );
  }

  return focusedFile ? (
    <div className="flex h-full min-h-0 flex-col">
      <FilePreviewBody key={focusedFile.filePath} file={focusedFile} compact mode="diff" />
    </div>
  ) : (
    <div className="flex h-full items-center justify-center px-6 text-center text-sm text-muted-foreground">
      {t('artifactPanel.changes.selectFileHint', '请点击对话中的文件卡片，或「查看文件变更」')}
    </div>
  );
}

interface PreviewTabProps {
  focusedFile: FilePreviewTarget | null;
}

function PreviewTab({ focusedFile }: PreviewTabProps) {
  const { t } = useTranslation('chat');
  if (!focusedFile) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-2 px-6 text-center">
        <p className="text-sm font-medium text-foreground">
          {t('artifactPanel.preview.emptyTitle', '尚未选择文件')}
        </p>
        <p className="max-w-md text-xs text-muted-foreground">
          {t(
            'artifactPanel.preview.emptyHint',
            '请先点击对话里的文件卡片打开侧栏并选中文件。',
          )}
        </p>
      </div>
    );
  }
  return <FilePreviewBody key={focusedFile.filePath} file={focusedFile} compact mode="preview" />;
}

export default ArtifactPanel;
